In [6]:
import pandas as pd
import os

In [8]:
path = "C:\\Users\\piercev1\\Documents\\Research\\Providence_Edinburgh_Genocide_Guidelines"

In [10]:
uppsala = pd.read_excel(os.path.join(path, "GEDEvent_v24_1.xlsx"))

In [11]:
uppsala.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
0,1568,ALG-1992-1-1-6,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-03-17,1,0,1,0,2,2,2,615,NaN
1,1572,ALG-1992-1-1-109,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-12-20,1,0,1,0,2,2,2,615,NaN
2,1593,ALG-1992-1-1-66,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-09-27,2,0,0,0,2,2,2,615,NaN
3,1624,ALG-1992-1-1-74,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-10-24,0,2,0,0,2,2,2,615,NaN
4,1632,ALG-1992-1-1-14,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-05-05,1,0,0,1,2,2,2,615,NaN

In [13]:
ewp2020 = pd.read_csv(os.path.join(path, "sra_2020.csv"))

In [14]:
ewp2020.head()

,country,SFTGcode,COW,risk_in_2019,risk_in_2019_20,anymk.ongoing,anymk.ever,reg.afr,reg.eap,reg.eur,...,freediscussion,social_inequality,even_civilrights,repress_civilsoc,social_power_dist,ses_power_dist,tradeshare.ln.combined,coup.try.5yr,polity2.fl.2,polity2.fl.3
0,Afghanistan,AFG,700,0.08977,0.2081,1,1,0,0,0,...,0.610,0,0,0,1,-0.910,-2.359148,0,1,0
1,Democratic Republic of Congo,ZAI,490,0.07177,0.1382,1,1,1,0,0,...,0.409,0,0,0,1,-0.695,-2.083498,0,1,0
2,Pakistan,PAK,770,0.06699,0.1794,1,1,0,0,0,...,0.547,0,0,0,1,-1.337,-3.111684,0,0,1
3,Yemen,YEM,679,0.06481,0.1840,0,0,0,0,0,...,0.231,1,0,0,1,-1.210,-2.803119,0,1,0
4,South Sudan,SSD,626,0.06471,0.1559,1,1,1,0,0,...,0.112,1,0,1,1,-1.664,-1.570666,0,1,0

In [15]:
ewp2021 = pd.read_csv(os.path.join(path, "sra_2021.csv"))

In [16]:
ewp2022 = pd.read_csv(os.path.join(path, "sra_2022.csv"))

In [17]:
ewp2023 = pd.read_csv(os.path.join(path, "sra_2023.csv"))

In [18]:
ewp2020['year'] = 2020

In [19]:
ewp2020.head()

,country,SFTGcode,COW,risk_in_2019,risk_in_2019_20,anymk.ongoing,anymk.ever,reg.afr,reg.eap,reg.eur,...,social_inequality,even_civilrights,repress_civilsoc,social_power_dist,ses_power_dist,tradeshare.ln.combined,coup.try.5yr,polity2.fl.2,polity2.fl.3,year
0,Afghanistan,AFG,700,0.08977,0.2081,1,1,0,0,0,...,0,0,0,1,-0.910,-2.359148,0,1,0,2020
1,Democratic Republic of Congo,ZAI,490,0.07177,0.1382,1,1,1,0,0,...,0,0,0,1,-0.695,-2.083498,0,1,0,2020
2,Pakistan,PAK,770,0.06699,0.1794,1,1,0,0,0,...,0,0,0,1,-1.337,-3.111684,0,0,1,2020
3,Yemen,YEM,679,0.06481,0.1840,0,0,0,0,0,...,1,0,0,1,-1.210,-2.803119,0,1,0,2020
4,South Sudan,SSD,626,0.06471,0.1559,1,1,1,0,0,...,1,0,1,1,-1.664,-1.570666,0,1,0,2020

In [20]:
ewp2021['year'] = 2021

In [21]:
ewp2022['year'] = 2022

In [22]:
ewp2023['year'] = 2023

In [23]:
cols2020 = set(ewp2020.columns)

In [24]:
cols2020

{'COW',
 'SFTGcode',
 'anymk.ever',
 'anymk.ongoing',
 'battledeaths.ln',
 'candidaterestriction',
 'country',
 'countryage.ln',
 'coup.try.5yr',
 'durable.ln',
 'elf.ethnic',
 'even_civilrights',
 'freediscussion',
 'freemove_men4',
 'freemove_women4',
 'gdppcgrowth.combined',
 'imr.sqrt',
 'includesnonstate',
 'ios.iccpr1',
 'judicialreform',
 'minorityrule',
 'partyban',
 'pol_killing_approved',
 'polity2.fl.2',
 'polity2.fl.3',
 'popsize.ln.combined',
 'reg.afr',
 'reg.eap',
 'reg.eur',
 'reg.mna',
 'reg.sca',
 'religiousfreedom',
 'repress_civilsoc',
 'risk_in_2019',
 'risk_in_2019_20',
 'ses_power_dist',
 'social_inequality',
 'social_power_dist',
 'tradeshare.ln.combined',
 'year'}

In [25]:
cols2021 = set(ewp2021.columns)

In [26]:
cols2022 = set(ewp2022.columns)

In [27]:
cols2023 = set(ewp2023.columns)

In [28]:
com_cols = cols2020 & cols2021 & cols2022 & cols2023

In [29]:
com_cols

{'COW',
 'SFTGcode',
 'anymk.ever',
 'anymk.ongoing',
 'battledeaths.ln',
 'candidaterestriction',
 'country',
 'countryage.ln',
 'coup.try.5yr',
 'elf.ethnic',
 'even_civilrights',
 'freediscussion',
 'freemove_men4',
 'freemove_women4',
 'gdppcgrowth.combined',
 'imr.sqrt',
 'includesnonstate',
 'ios.iccpr1',
 'judicialreform',
 'minorityrule',
 'partyban',
 'pol_killing_approved',
 'popsize.ln.combined',
 'reg.afr',
 'reg.eap',
 'reg.eur',
 'reg.mna',
 'reg.sca',
 'religiousfreedom',
 'repress_civilsoc',
 'ses_power_dist',
 'social_inequality',
 'social_power_dist',
 'tradeshare.ln.combined',
 'year'}

In [31]:
ewp2020_r = ewp2020[list(com_cols)]

In [32]:
ewp2020_r.head()

,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,social_inequality,country,COW,...,candidaterestriction,social_power_dist,ses_power_dist,year,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln
0,1,1,0,0,0,0,0,0,Afghanistan,700,...,1,1,-0.910,2020,0.001816,17.427736,-2.359148,2,4.605170,10.153468
1,1,1,0,0,0,0,1,0,Democratic Republic of Congo,490,...,1,1,-0.695,2020,0.040775,18.240043,-2.083498,3,4.077537,6.042633
2,1,1,0,0,0,0,0,0,Pakistan,770,...,1,1,-1.337,2020,0.038073,19.164214,-3.111684,1,4.276666,5.293305
3,0,0,0,0,1,0,0,1,Yemen,679,...,1,1,-1.210,2020,-0.028943,17.164070,-2.803119,0,3.367296,8.417152
4,1,1,0,0,0,0,1,1,South Sudan,626,...,1,1,-1.664,2020,-0.006500,16.223777,-1.570666,2,2.079442,6.285998

In [33]:
ewp2021_r = ewp2021[list(com_cols)]

In [34]:
ewp2022_r = ewp2022[list(com_cols)]

In [35]:
ewp2023_r = ewp2023[list(com_cols)]

In [37]:
ewp = pd.concat([ewp2020_r, ewp2021_r, ewp2022_r, ewp2023_r], axis = 0)

In [38]:
ewp

,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,social_inequality,country,COW,...,candidaterestriction,social_power_dist,ses_power_dist,year,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln
0,1,1,0,0,0,0,0,0,Afghanistan,700,...,1,1,-0.910,2020,0.001816,17.427736,-2.359148,2,4.605170,10.153468
1,1,1,0,0,0,0,1,0,Democratic Republic of Congo,490,...,1,1,-0.695,2020,0.040775,18.240043,-2.083498,3,4.077537,6.042633
2,1,1,0,0,0,0,0,0,Pakistan,770,...,1,1,-1.337,2020,0.038073,19.164214,-3.111684,1,4.276666,5.293305
3,0,0,0,0,1,0,0,1,Yemen,679,...,1,1,-1.210,2020,-0.028943,17.164070,-2.803119,0,3.367296,8.417152
4,1,1,0,0,0,0,1,1,South Sudan,626,...,1,1,-1.664,2020,-0.006500,16.223777,-1.570666,2,2.079442,6.285998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,0,0,1,1,0,0,0,0,Lithuania,368,...,1,0,1.388,2023,0.034557,14.919486,-1.209574,4,3.433987,0.000000
158,0,0,1,1,0,0,0,0,Denmark,390,...,1,0,1.847,2023,0.032002,15.615046,-1.575342,4,6.963190,0.000000
159,0,0,1,1,0,0,0,0,Norway,385,...,1,0,2.383,2023,0.025650,15.538799,-2.087887,4,4.762174,0.000000
160,0,0,1,1,0,0,0,0,Estonia,366,...,1,0,1.436,2023,0.062133,14.263249,-1.180223,4,3.433987,0.000000
161,0,0,1,1,0,0,0,0,Slovenia,349,...,1,0,1.181,2023,0.060197,14.663403,-1.173667,4,3.433987,0.000000

In [47]:
cols_to_move = ['country', 'COW', 'year']

In [48]:
remaining_cols = [col for col in ewp.columns if col not in cols_to_move]

In [49]:
new_order = cols_to_move + remaining_cols

In [50]:
new_order

['country',
 'COW',
 'year',
 'anymk.ongoing',
 'anymk.ever',
 'freemove_men4',
 'freemove_women4',
 'reg.mna',
 'reg.eap',
 'reg.afr',
 'social_inequality',
 'includesnonstate',
 'SFTGcode',
 'pol_killing_approved',
 'judicialreform',
 'reg.eur',
 'even_civilrights',
 'elf.ethnic',
 'reg.sca',
 'minorityrule',
 'ios.iccpr1',
 'coup.try.5yr',
 'repress_civilsoc',
 'freediscussion',
 'imr.sqrt',
 'partyban',
 'candidaterestriction',
 'social_power_dist',
 'ses_power_dist',
 'gdppcgrowth.combined',
 'popsize.ln.combined',
 'tradeshare.ln.combined',
 'religiousfreedom',
 'countryage.ln',
 'battledeaths.ln']

In [51]:
ewp = ewp[new_order]

In [52]:
ewp.head()

,country,COW,year,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,...,partyban,candidaterestriction,social_power_dist,ses_power_dist,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln
0,Afghanistan,700,2020,1,1,0,0,0,0,0,...,4,1,1,-0.910,0.001816,17.427736,-2.359148,2,4.605170,10.153468
1,Democratic Republic of Congo,490,2020,1,1,0,0,0,0,1,...,4,1,1,-0.695,0.040775,18.240043,-2.083498,3,4.077537,6.042633
2,Pakistan,770,2020,1,1,0,0,0,0,0,...,4,1,1,-1.337,0.038073,19.164214,-3.111684,1,4.276666,5.293305
3,Yemen,679,2020,0,0,0,0,1,0,0,...,4,1,1,-1.210,-0.028943,17.164070,-2.803119,0,3.367296,8.417152
4,South Sudan,626,2020,1,1,0,0,0,0,1,...,3,1,1,-1.664,-0.006500,16.223777,-1.570666,2,2.079442,6.285998

In [53]:
ewp.to_csv(os.path.join(path, 'ewp.csv'), index = False)

In [54]:
uppsala.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
0,1568,ALG-1992-1-1-6,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-03-17,1,0,1,0,2,2,2,615,NaN
1,1572,ALG-1992-1-1-109,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-12-20,1,0,1,0,2,2,2,615,NaN
2,1593,ALG-1992-1-1-66,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-09-27,2,0,0,0,2,2,2,615,NaN
3,1624,ALG-1992-1-1-74,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-10-24,0,2,0,0,2,2,2,615,NaN
4,1632,ALG-1992-1-1-14,1992,True,Clear,1,386,386,Algeria: Government,828,...,1992-05-05,1,0,0,1,2,2,2,615,NaN

In [55]:
uppsala.tail()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
349728,515726,RUS-2023-1-14117-791.1,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-03-10,0,2,0,0,2,2,2,365,369.0
349729,515884,RUS-2022-1-14117-992,2022,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2022-12-16,0,1,0,0,1,1,1,365,369.0
349730,515995,ISR-2023-1-477-1247,2023,True,Clear,1,234,234,Israel: Palestine,477,...,2023-10-07,1,0,0,0,1,1,1,666,NaN
349731,516027,RUS-2023-1-14117-793,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-12-31,6,0,0,0,6,7,6,365,369.0
349732,516031,FRN-2023-2-17630-45,2023,True,Clear,2,17630,16009,DZ Mafia - Yoda,17630,...,2023-05-03,0,2,0,0,2,2,2,NaN,NaN

In [56]:
type(uppsala.year)

pandas.core.series.Series

In [57]:
years = [2020, 2021, 2022, 2023]

In [59]:
mask = uppsala['year'].isin(years)

In [98]:
uppsala_filtered = uppsala[mask]

In [61]:
uppsala_filtered

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
267518,320838,SYR-2020-1-11973-0,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,0,0,12,0,12,12,12,652,NaN
267551,320874,SYR-2020-1-11973-5,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,2,0,0,0,2,2,2,652,NaN
267552,320875,AFG-2020-2-14637-1,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267570,320896,SYR-2020-3-14200-0,2020,False,Clear,3,4456,13299,Syrian insurgents - Civilians,4456,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267571,320897,AFG-2020-2-14637-0,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,1,0,0,0,1,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349728,515726,RUS-2023-1-14117-791.1,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-03-10,0,2,0,0,2,2,2,365,369.0
349729,515884,RUS-2022-1-14117-992,2022,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2022-12-16,0,1,0,0,1,1,1,365,369.0
349730,515995,ISR-2023-1-477-1247,2023,True,Clear,1,234,234,Israel: Palestine,477,...,2023-10-07,1,0,0,0,1,1,1,666,NaN
349731,516027,RUS-2023-1-14117-793,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-12-31,6,0,0,0,6,7,6,365,369.0
349732,516031,FRN-2023-2-17630-45,2023,True,Clear,2,17630,16009,DZ Mafia - Yoda,17630,...,2023-05-03,0,2,0,0,2,2,2,NaN,NaN

In [80]:
uppsala_filtered.to_excel(uppsala_filtered, os.path.join(path, 'uppsala_filtered.xlsx'))

ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>

In [63]:
conflicts = uppsala_filtered.conflict_name.unique()

In [64]:
len(conflicts)

515

In [66]:
conflicts

array(['Syria: Government', 'IS - SDF', 'Syrian insurgents - Civilians',
       'SNA - SDF', 'IS - Civilians', 'SDF - Civilians',
       'Afghanistan: Government', 'Afghanistan: Islamic State',
       'Burkina Faso: Islamic State', 'Burkina Faso: Government',
       'Syria: Islamic State',
       'Jalisco Cartel New Generation - Sinaloa Cartel',
       'India - Pakistan', 'Comando Vermelho - Terceiro Comando Puro',
       'Jalisco Cartel New Generation - Zetas Vieja Escuela',
       'Mozambique: Islamic State', 'India: Kashmir',
       'India: Western South East Asia', 'Turkey: Kurdistan',
       'Al-Shabaab - Civilians', 'Nigeria: Government',
       'Somalia: Government', 'Kenya: Northeastern Province and Coast',
       'Ethiopia: Oromiya', 'JAS - Civilians', 'Nigeria: Islamic State',
       'Cameroon: Ambazonia', 'Iran - Israel',
       'Government of Syria - Civilians', 'IS - HTS', 'India: Government',
       'CPI-Maoist - Civilians', 'APCLS, CMC - NDC-R',
       'CNPSC - Ngumino, Twiganeho', 'Rwanda: Government',
       'DR Congo (Zaire): Government', 'Thailand: Patani',
       'NDC-R - Civilians', 'CMC - NDC-R', 'CMC - Civilians',
       'Government of DR Congo (Zaire) - Civilians', 'ALC - Civilians',
       'URDPC - Civilians', 'DR Congo (Zaire): Islamic State',
       'Mali: Government', 'Luba - Batwa', 'Beni Amir - Nuba',
       'JNIM - Civilians', 'Government of South Sudan - Civilians',
       'Government of Mali - Civilians', 'Dozos (Mali) - Civilians',
       'Mali: Islamic State', 'Taleban - Civilians',
       'Misseriya - Ngok Dinka', 'Government of Nigeria - Civilians',
       'Jalisco Cartel New Generation - Santa Rosa de Lima Cartel',
       'Juarez Cartel - Sinaloa Cartel', 'Los Zetas - Civilians',
       'Niger: Islamic State', "Al-Shabaab - Ma'awisley",
       'Fulani - Mwaghavul', 'Government of Burundi - Civilians',
       'Government of Kenya - Civilians', 'Pokot - Turkana',
       'Majerteen subclan (Darod) - Awramale subclan (Darod)',
       'IS - Yan Gora', 'Agworok (Atyap) - Fulani',
       'Government of Ethiopia - Civilians', 'Atyap - Fulani',
       'FDLR-FOCA - Civilians', 'Government of Afghanistan - Civilians',
       'Twiganeho - Civilians', 'CNPSC - Ngumino', 'IS - JAS',
       'Fulani - Tiv', 'APCLS - NDC-R', 'Yemen (North Yemen): Government',
       'Libya: Government', 'Central African Republic: Government',
       'FPRC - MLCJ', 'anti-Balaka - FPRC', 'anti-Balaka - Civilians',
       'anti-Balaka - MPC', 'Chad: Islamic State', 'Black Axe - Eyie',
       'Supporters of APC - Supporters of PDP', 'Jukun - Tiv',
       'Government of Cameroon - Civilians',
       'Ambazonia insurgents - Civilians', 'Iraq: Government',
       'Government of Iraq - Civilians', 'Myanmar (Burma): Karen',
       'Algeria: Islamic State', 'Algeria: Government',
       'Forces of the Presidential Leadership Council - STC',
       'Pakistan: Balochistan', 'TTP - Civilians', 'Pakistan: Government',
       'Pakistan: Islamic State', 'AQAP - IS',
       'Yemen (North Yemen): Islamic State',
       'AQAP - Forces of the Presidential Leadership Council',
       'Chad: Government', 'Christians (Nigeria) - Muslims (Nigeria)',
       'Dan na Ambassagou - Civilians', 'Colombia: Government',
       'Atakar - Fulani', 'FARC-EMC - Civilians',
       'Government of Colombia - Civilians', 'Somalia: Islamic State',
       'Somalia: Somaliland', 'Kashmir insurgents - Civilians',
       'Perci (Batwa militia) - Civilians',
       'Elements (Luba militia) - Civilians', 'Dogon - Fulani',
       'Government of Sudan - Civilians', 'Comando Vermelho - GDE',
       'CNPSC - Civilians', 'CRAC-PF - Los Ardillos',
       'Agar Dinka - Gok Dinka', 'Tunisia: Government',
       'Egypt: Islamic State', 'Central African Republic: Logone',
       'FPRC - Civilians', 'Koglweogo - Civilians', 'Dozos (Mali) - JNIM',
       'Israel: Palestine', 'Fulani - Irigwe',
       'DR Congo (Zaire): Katanga', 'DR Congo (Zaire): Kongo Kingdom',
       'Niger: Government', 'Government of South Africa - Civilians',
       'Lou Nuer - Murle', 'Arab - Zaghawa',
       'Mayi Mayi Mazembe - Civilians', 'Bor Dinka, Lou Nuer - Murle',
       'Gak Dinka - Manuer Dinka', 'FDBC - Civilians', 'CPP - Civilians',
       'Philippines: Mindanao', 'Philippines: Government',
       'Philippines: Islamic State', 'Iran: Government',
       'Myanmar (Burma): Arakan', 'Government of Niger - Civilians',
       'Government of Yemen (North Yemen) - Civilians', 'Afar - Oromo',
       'Myanmar (Burma): Government', 'Afar - Issa (Dir)',
       'Amhara - Gumuz', 'Amhara - Oromo', 'Tunisia: Islamic State',
       'Government of Burkina Faso - Civilians', 'Myanmar (Burma): Shan',
       'Azerbaijan: Artsakh (Nagorno-Karabakh)', 'FPRC - MLCJ, RPRC',
       '3R - Civilians', 'Ukraine: Novorossiya',
       'Israel: Southern Lebanon', 'Russia: Islamic State', 'IS - JNIM',
       'PKK - Civilians', 'Indonesia: West Papua', 'OPM - Civilians',
       'Cameroon: Government', 'Jole - Shomo',
       'Syria: Government/Rojava Kurdistan', 'FRPI - Civilians',
       'Burundi: Government',
       'Ahrar al-Sharqiya - al-Moutasem Brigade, Hamza Division',
       'AFP-Gutabara, Ngumino, Twiganeho - CNPSC',
       'FPP-AP - Mayi Mayi Mazembe, NDC-R',
       'Government of Somalia - Civilians',
       'Jalisco Cartel New Generation - La Nueva Familia',
       'BeltrÃ¡n Leyva Cartel - Sinaloa Cartel',
       'Sinaloa Cartel - Los Chapitos - Sinaloa Cartel - Los Mayos',
       'Jalisco Cartel New Generation - Los Zetas',
       'Jalisco Cartel New Generation - Los Rojos',
       'Caborca Cartel, Sinaloa Cartel - Los Mayos - Sinaloa Cartel - Los Chapitos',
       'Gulf Cartel - Los Zetas', 'Guerreros Unidos - Los Tlacos',
       'OLA - Civilians', 'Government of Mozambique - Civilians',
       'Fulani - Kadara', 'Cartel del Sur - Los Rojos',
       'Panyar Dinka - Waat Dinka', 'Government of Mexico - Civilians',
       'Gulf Cartel - Jalisco Cartel New Generation',
       'Bul Nuer - Twic Dinka', 'Gulf Cartel - Sinaloa Cartel',
       'Angola: Cabinda', 'NAS - SPLM/A - IO',
       'Fuerza Anti UniÃ³n  - La Union de Tepito',
       'Jalisco Cartel New Generation - Nueva Plaza Cartel',
       'FPRC - MLCJ, PRNC, RPRC', 'Misseriya - Nuer',
       'South Sudan: Government',
       'Government of Myanmar (Burma) - Civilians',
       'Government of Philippines - Civilians',
       'Jalisco Cartel New Generation - La Familia',
       'Jalisco Cartel New Generation - Civilians',
       'Cameroon: Islamic State', 'JNIM - Koglweogo',
       'Government of India - Civilians', 'Dan na Ambassagou - JNIM',
       'Government of Rwanda - Civilians', 'RMDC - Civilians',
       'Government of Mauritania - Civilians', 'Yan Sakai - Civilians',
       'Ichen - Tiv', 'Chabo - Hausa', 'Fulani - Rizeigat Baggara',
       'Hawazma - Nuba', 'JAS - Yan Gora',
       'Government of Israel - Civilians',
       'Government of Iran - Civilians', 'Fulani - Yoruba',
       'Afar - Somali', 'Government of Russia (Soviet Union) - Civilians',
       'Senegal: Casamance', 'Borana - Degodia',
       'Amhara, Guraghe - Oromo', 'Deebam - NDV', 'SLM/A - Civilians',
       'Bor Dinka - Murle', 'Bor Dinka, Gawaar Nuer, Lou Nuer - Murle',
       'Lunguda - Waja', 'Apuk Padoc - Atok Buk', 'CNPSC - Twiganeho',
       'Government of Liberia - Civilians', 'NDC-R - NDC-R-GBS',
       'URDPC - Zaire self-defense group', 'Igbo - Fulani',
       'Birom - Fulani', 'HTS - Tanzim Hurras ad-Din',
       'Mayi Mayi Simba - Civilians', 'China - India', 'CATA  - Codeta',
       'Bassa Kwomu - Egbura Mozum', 'Ale - Konso',
       'CODECO-BTD - Civilians', 'Sudan: Government', 'Arab - Masalit',
       'Mahariya, Mima - Masalit', 'Eggon - Fulani',
       'Zaire self-defense group - Civilians',
       'FPIC Chambre noire sanduku - Civilians', 'Uganda: Government',
       'Torma - Torma Manian', 'MAA - CMA', 'anti-Balaka - UPC',
       'ComitÃ©s locaux de vigilance - JAS',
       'Government of Venezuela - Civilians', 'RED-TABARA  - Civilians',
       'CNPSC - Mayi Mayi Biloze Bishambuke',
       'Government of Peru - Civilians',
       'United States of America: Government',
       'Government of Central African Republic - Civilians',
       'India: Nagaland', 'UPC - Civilians',
       'Government of eSwatini (Swaziland) - Civilians',
       'AFP-Gutabara, Ngumino, Twiganeho - Civilians',
       'Los Zetas - CÃ¡rtel del Noreste faction - Zetas Vieja Escuela',
       'ELN - Civilians', 'AGC - Civilians',
       'Forces of the House of Representatives - IS',
       'Greenlanders - NDV', 'Lebanon: Islamic State',
       'Bakassi boys - Civilians', 'Hindus (India) - Muslims (India)',
       'Sinaloa Cartel - Civilians', 'G9 an Fanmi e Alye - Civilians',
       'Delmas 19 gang , Delmas 6 gang, Delmas 95 gang, Nan Barozi gang, Nan Belekou gang, Nan Boston gang, Nan ChabÃ³n gang, Nan Ti Bwa gang, Pilate Base gang, Simon Pele gang, Wharf de Jeremie gang - Civilians',
       'Comando Vermelho - FDN', 'Government of Egypt - Civilians',
       'PLFI - Civilians', 'Government of Indonesia - Civilians',
       'Ayiel Dinka - Pagok Dinka', 'Iran: Kurdistan',
       'Agaw, Amhara - Gumuz', 'Government of Angola - Civilians',
       'Marakwet - Pokot', 'Kpelle - Konianke, MalinkÃ©',
       'Government of Haiti - Civilians',
       'Carteles Unidos - Jalisco Cartel New Generation',
       'Comando Vermelho - Civilians', 'Tanzania: Islamic State',
       'Fulani - Masalit', 'Government of Tanzania - Civilians',
       'Hutu - Nande', 'Los Ardillos - Los Rojos',
       'Government of Zimbabwe (Rhodesia) - Civilians',
       'Government of Ivory Coast - Civilians', 'Hausa - Yoruba',
       'SLM/A - MA - SLM/A - SB', 'AFP-Gutabara - CNPSC',
       'FPP-AP - NDC-R', 'LRA - Civilians', 'Ethiopia: Government',
       'IS - Taleban', 'Black Axe - Maphite',
       'Government of Madagascar - Civilians', 'FPRC - UPC',
       'FARC-EMC - ELN', 'Frente Oliver Sinisterra  - Civilians',
       'Cartel Independiente de Acapulco - Los Virus',
       'Patani insurgents - Civilians',
       'FPIC Chambre noire sanduku, URDPC - Civilians', 'Arab - Bulala',
       'Bangladesh: Chittagong Hill Tracts',
       'Amhara, Oromo, Shinasha - Gumuz', 'Myanmar (Burma): Kachin',
       "Dir clan  - Sa'ad subclan of Habar Gidir clan (Hawiye)",
       'PCC - Civilians', 'Government of Eritrea - Civilians',
       'Government of Eritrea, Government of Ethiopia - Civilians',
       'TPLF - Civilians',
       'Morocco: Sahrawi Arab Democratic Republic (Western Sahara)',
       'Benin: Government', 'AGC - ELN',
       'Mara 18 (Honduras) - Mara Salvatrucha (Honduras)',
       '400 Mawozo  - Civilians', 'PCC - Sindicato do Crime',
       'CPC - Civilians', 'AssociaÃ§Ã£o FamÃ­lia Capixaba - PCC',
       'Turkey: Government', 'Iyeke (Batwa) - Nkundo',
       'Anti-Bala - Bala na Cara', 'Comando Vermelho - PCC',
       'Bonde do Maluco - Comando da Paz', 'Bonde do Maluco - Civilians',
       'Bonde do Maluco - Comando Vermelho', 'Ajeita - Bonde do Maluco',
       'GDE, PCC - Sindicato do Crime',
       'Bonde dos 13, PCC - Comando Vermelho',
       'Bonde dos 40 - Comando Vermelho', 'Bonde dos 40 - PCC',
       'Government of Brazil - Civilians', 'Bonde dos 40 - PCM',
       'Cartel Independiente de Acapulco - Jalisco Cartel New Generation',
       'Supporters of Awami League - Supporters of BNP', 'Ezza - Korri',
       'Agaw, Amhara, Shinasha - Gumuz',
       'Mayi Mayi Biloze Bishambuke - Twiganeho',
       'Los Choneros - Los Chone Killers , Los Lobos , Los Pipos, Los Tiguerones',
       'IS - MSA', 'Luac Jang Dinka - Thiyic Dinka', 'IPOB - Civilians',
       'Al-Khobar - Civilians', 'OLA - Fekade Abdisa faction - Civilians',
       'Toposa - Buya', 'FPP-AP, NDC-R-GBS - NDC-R',
       'Grupo Escorpion - Gulf Cartel - Los Ciclones faction',
       'Nigeria: Biafra', 'Los Colombianos - Los Mayas', 'Agarabi - Tapo',
       'Mayi Mayi Kirikicho, Raia Mutomboki Butachibera, Raia Mutomboki Hama Kombo - Nyatura Turarambiwe',
       'Myanmar (Burma): Kokang', 'Kpelle - MalinkÃ©',
       'G9 an Fanmi e Alye - G Pep', 'Nyangatom  - Turkana',
       'Arab - Kagal, Kibete', 'Kyrgyzstan - Tajikistan',
       'Government of Uganda - Civilians',
       'AFP-Gutabara, Ngumino - Civilians', 'Myanmar (Burma): Karenni',
       'Taleban - High Council of Afghanistan Islamic Emirate',
       'Iran: Islamic State', 'Hausa - Funj', 'Gawaar Nuer - Murle',
       'Peru:Government', 'Fulani - Izzi (Igbo)', 'Uganda: Islamic State',
       'KNU - Civilians', 'Abugbe (Agatu) - Agbaduma (Agatu)',
       'Mara Salvatrucha (El Salvador) - Civilians',
       'Libya: Islamic State', 'Fulani - Taisha',
       'Gony Dinka - Thiyic Dinka', 'NUG - Civilians', 'UBA - Civilians',
       'Borana - Gabra', 'Bonta Boys - Civilians', 'Balanda - Azande',
       'Luac Jang Dinka - Lou Paher', 'Cie Kho - Cie Guandong',
       'LeJ - Civilians', 'India: Tripura', 'Choa Arab - Musgum',
       'Dar Ali (Hawazma) - Kenana', 'Janjaweed  - Civilians',
       'Luac Jang Dinka - Lou Paher, Thiyic Dinka',
       'Government of Chad - Civilians',
       'Kawahla, Kenana, Nuba Logan - Dar Ali (Hawazma)',
       'Black - Indian', 'Los Choneros - Los Lobos',
       'FPIC Chambre noire sanduku - URDPC', 'NSCN-IM - Civilians',
       'ARSA - Civilians', 'Cartel do Norte - Comando Vermelho',
       'Nova Okaida - Estados Unidos', 'Choa Arab - Kotoko',
       'IS - Banibangou Vigilance Committee',
       'AFP-Gutabara - Mayi Mayi Biloze Bishambuke',
       'Los Ardillos - Los Tlacos', 'Misseriya - Arab',
       'Misseriya Jebel  - Rizeigat', 'PIJ - Civilians',
       'Gulf Cartel - Los Zetas - CÃ¡rtel del Noreste faction',
       'Toposa - Turkana', 'Al-Shabaab - IS',
       'Cartel Independiente de Colima - Jalisco Cartel New Generation',
       'FDBC - Zaire self-defense group', 'Murle - Nuer',
       'Kusasi - Mamprusi',
       'Cartel Independiente de Acapulco - Los Rusos, UPOEG',
       'Jalisco Cartel New Generation, Sangre Nueva Zeta - Los Rojos',
       'Bonde do Maluco - Katiara', 'Russia - Ukraine',
       'Jalisco Cartel New Generation - PÃ¡jaros Sierra',
       'Nambelo Lohembe sector - Vunge sector', 'Agatu - Fulani',
       'Amigos Para Sempre - FamÃ­lia Terror AmapÃ¡', 'Deebam - Deewell',
       'Farmers (Chad) - Herders (Chad)', 'Los Zetas - Sinaloa Cartel',
       'GATIA, MSA - IS', 'Los Ardillos - Civilians', 'M23 - Civilians',
       'Fulani - Rizeigat', 'Fano - Civilians', 'RCSS - UWSA',
       'Los Lobos  - R7', 'Government of Sierra Leone - Civilians',
       'Chawai - Fulani', 'Aiyala - Nomali',
       'Ikot-Offiong community - Oku Iboku community',
       'Twic Dinka - Ngok Dinka', 'GATIA - IS',
       'Government of Nepal - Civilians', 'Togo: Government',
       'Fulani - Idoma', 'Burji - Guji', 'Gimir - Awlad Zeid',
       'FPIC Chambre noire sanduku - FRPI',
       'Mara Salvatrucha (Honduras) - Civilians',
       'Buya, Murle, Tenet - Toposa', 'Giants Brigade, STC - Islah',
       'Teke - Yaka', 'Government of Papua New Guinea - Civilians',
       'Government of Bangladesh - Civilians',
       'Amigos dos Amigos - Comando Vermelho',
       'Mara 18 (Guatemala) - Mara Salvatrucha (Guatemala)',
       'SPLM/A - IO - Kitgwang - SPLM/A - IO - Olony',
       'Misseriya - Hamar', 'Mayi Mayi Chini ya Tuna - Civilians',
       'Kuboma - Kulumata', 'Kata Katanga - Civilians',
       'Comando Vermelho - Massa', 'Ijaw - Ilaje',
       '400 Mawozo  - Kraze BaryÃ¨',
       'ANCDH/AFDP, APCLS, CMC, FPP-AP, NDC-R - M23', 'IS - Naparama',
       'Renamo - Civilians', 'Misseriya - Awlad Rashid', 'FDN - PCC',
       'Luac Jang Dinka - Baac', 'Apuk Padoc - Nuer', 'Nova Okaida - PCC',
       'VDP - Civilians', 'Luac Jang Dinka - Pakam Dinka',
       'SSC-Khatumo Administration - Republic of Somaliland',
       'Mozambique: Government', 'Daoussak (Tuareg) - Fulani',
       'Hamas - Civilians', 'Bonde dos 40 - Civilians', 'VHP - Civilians',
       'Russia (Soviet Union): Government', 'M23 - VDP',
       'Mauritania: Government', 'Comando Vermelho - Holanda',
       'Mobondo - Civilians', 'Azande Ani Kpi Gbe - CPC',
       'Carteles Unidos, Guerreros Unidos - Los Tlacos', 'Fulani - Kuteb',
       'Kuki - Meitei', 'Los Rusos, UPOEG - Los Tlacos',
       'Lengola - Mbole', 'Government of Tajikistan - Civilians',
       'Karimjo - Wurukum', 'Hausa - Nuba',
       'Shia (Pakistan) - Sunni (Pakistan)', 'Djerma (Zherma) - Fulani',
       'Anuak - Nuer', 'Ethiopia: Government/Amhara', 'RSF - Civilians',
       'Dinka  - Nuer', 'Los Lobos  - Los Tiguerones',
       'Mali: Government/Azawad', 'Banunu - Batende',
       'Russia (Soviet Union): Chechnya',
       'Beni Halba Baggara - Salamat Baggara',
       'Deir ez Zor Military Council - SDF',
       '5 segon, Canaan 2 gang  - Civilians',
       'Supporters of Awami League - Supporters of Jamaat-e-Islami',
       'AGC - ELN, FARC-EMC', 'Grand Ravine gang - Civilians',
       'DZ Mafia - Yoda', 'Los Costenos - Los Pepes',
       'Habaniya  - Salamat Baggara', 'Chain Guys  - Full Force',
       'Terre Noire - Civilians', 'G Pep - Civilians', 'Arab - Gimir',
       'Fulani - Mwaghavul , Ron'], dtype=object)

In [67]:
import re

In [68]:
pattern = r'^[\w-]+'

In [69]:
def extract_first_word(string):
    match = re.search(pattern, string)
    if match:
        return match.group(0)
    else:
        return ''

In [70]:
countries = [extract_first_word(string) for string in conflicts]

In [71]:
countries

['Syria',
 'IS',
 'Syrian',
 'SNA',
 'IS',
 'SDF',
 'Afghanistan',
 'Afghanistan',
 'Burkina',
 'Burkina',
 'Syria',
 'Jalisco',
 'India',
 'Comando',
 'Jalisco',
 'Mozambique',
 'India',
 'India',
 'Turkey',
 'Al-Shabaab',
 'Nigeria',
 'Somalia',
 'Kenya',
 'Ethiopia',
 'JAS',
 'Nigeria',
 'Cameroon',
 'Iran',
 'Government',
 'IS',
 'India',
 'CPI-Maoist',
 'APCLS',
 'CNPSC',
 'Rwanda',
 'DR',
 'Thailand',
 'NDC-R',
 'CMC',
 'CMC',
 'Government',
 'ALC',
 'URDPC',
 'DR',
 'Mali',
 'Luba',
 'Beni',
 'JNIM',
 'Government',
 'Government',
 'Dozos',
 'Mali',
 'Taleban',
 'Misseriya',
 'Government',
 'Jalisco',
 'Juarez',
 'Los',
 'Niger',
 'Al-Shabaab',
 'Fulani',
 'Government',
 'Government',
 'Pokot',
 'Majerteen',
 'IS',
 'Agworok',
 'Government',
 'Atyap',
 'FDLR-FOCA',
 'Government',
 'Twiganeho',
 'CNPSC',
 'IS',
 'Fulani',
 'APCLS',
 'Yemen',
 'Libya',
 'Central',
 'FPRC',
 'anti-Balaka',
 'anti-Balaka',
 'anti-Balaka',
 'Chad',
 'Black',
 'Supporters',
 'Jukun',
 'Government',
 'Ambazonia',
 'Iraq',
 'Government',
 'Myanmar',
 'Algeria',
 'Algeria',
 'Forces',
 'Pakistan',
 'TTP',
 'Pakistan',
 'Pakistan',
 'AQAP',
 'Yemen',
 'AQAP',
 'Chad',
 'Christians',
 'Dan',
 'Colombia',
 'Atakar',
 'FARC-EMC',
 'Government',
 'Somalia',
 'Somalia',
 'Kashmir',
 'Perci',
 'Elements',
 'Dogon',
 'Government',
 'Comando',
 'CNPSC',
 'CRAC-PF',
 'Agar',
 'Tunisia',
 'Egypt',
 'Central',
 'FPRC',
 'Koglweogo',
 'Dozos',
 'Israel',
 'Fulani',
 'DR',
 'DR',
 'Niger',
 'Government',
 'Lou',
 'Arab',
 'Mayi',
 'Bor',
 'Gak',
 'FDBC',
 'CPP',
 'Philippines',
 'Philippines',
 'Philippines',
 'Iran',
 'Myanmar',
 'Government',
 'Government',
 'Afar',
 'Myanmar',
 'Afar',
 'Amhara',
 'Amhara',
 'Tunisia',
 'Government',
 'Myanmar',
 'Azerbaijan',
 'FPRC',
 '3R',
 'Ukraine',
 'Israel',
 'Russia',
 'IS',
 'PKK',
 'Indonesia',
 'OPM',
 'Cameroon',
 'Jole',
 'Syria',
 'FRPI',
 'Burundi',
 'Ahrar',
 'AFP-Gutabara',
 'FPP-AP',
 'Government',
 'Jalisco',
 'BeltrÃ¡n',
 'Sinaloa',
 'Jalisco',
 'Jalisco',
 'Caborca',
 'Gulf',
 'Guerreros',
 'OLA',
 'Government',
 'Fulani',
 'Cartel',
 'Panyar',
 'Government',
 'Gulf',
 'Bul',
 'Gulf',
 'Angola',
 'NAS',
 'Fuerza',
 'Jalisco',
 'FPRC',
 'Misseriya',
 'South',
 'Government',
 'Government',
 'Jalisco',
 'Jalisco',
 'Cameroon',
 'JNIM',
 'Government',
 'Dan',
 'Government',
 'RMDC',
 'Government',
 'Yan',
 'Ichen',
 'Chabo',
 'Fulani',
 'Hawazma',
 'JAS',
 'Government',
 'Government',
 'Fulani',
 'Afar',
 'Government',
 'Senegal',
 'Borana',
 'Amhara',
 'Deebam',
 'SLM',
 'Bor',
 'Bor',
 'Lunguda',
 'Apuk',
 'CNPSC',
 'Government',
 'NDC-R',
 'URDPC',
 'Igbo',
 'Birom',
 'HTS',
 'Mayi',
 'China',
 'CATA',
 'Bassa',
 'Ale',
 'CODECO-BTD',
 'Sudan',
 'Arab',
 'Mahariya',
 'Eggon',
 'Zaire',
 'FPIC',
 'Uganda',
 'Torma',
 'MAA',
 'anti-Balaka',
 'ComitÃ©s',
 'Government',
 'RED-TABARA',
 'CNPSC',
 'Government',
 'United',
 'Government',
 'India',
 'UPC',
 'Government',
 'AFP-Gutabara',
 'Los',
 'ELN',
 'AGC',
 'Forces',
 'Greenlanders',
 'Lebanon',
 'Bakassi',
 'Hindus',
 'Sinaloa',
 'G9',
 'Delmas',
 'Comando',
 'Government',
 'PLFI',
 'Government',
 'Ayiel',
 'Iran',
 'Agaw',
 'Government',
 'Marakwet',
 'Kpelle',
 'Government',
 'Carteles',
 'Comando',
 'Tanzania',
 'Fulani',
 'Government',
 'Hutu',
 'Los',
 'Government',
 'Government',
 'Hausa',
 'SLM',
 'AFP-Gutabara',
 'FPP-AP',
 'LRA',
 'Ethiopia',
 'IS',
 'Black',
 'Government',
 'FPRC',
 'FARC-EMC',
 'Frente',
 'Cartel',
 'Patani',
 'FPIC',
 'Arab',
 'Bangladesh',
 'Amhara',
 'Myanmar',
 'Dir',
 'PCC',
 'Government',
 'Government',
 'TPLF',
 'Morocco',
 'Benin',
 'AGC',
 'Mara',
 '400',
 'PCC',
 'CPC',
 'AssociaÃ§Ã£o',
 'Turkey',
 'Iyeke',
 'Anti-Bala',
 'Comando',
 'Bonde',
 'Bonde',
 'Bonde',
 'Ajeita',
 'GDE',
 'Bonde',
 'Bonde',
 'Bonde',
 'Government',
 'Bonde',
 'Cartel',
 'Supporters',
 'Ezza',
 'Agaw',
 'Mayi',
 'Los',
 'IS',
 'Luac',
 'IPOB',
 'Al-Khobar',
 'OLA',
 'Toposa',
 'FPP-AP',
 'Grupo',
 'Nigeria',
 'Los',
 'Agarabi',
 'Mayi',
 'Myanmar',
 'Kpelle',
 'G9',
 'Nyangatom',
 'Arab',
 'Kyrgyzstan',
 'Government',
 'AFP-Gutabara',
 'Myanmar',
 'Taleban',
 'Iran',
 'Hausa',
 'Gawaar',
 'Peru',
 'Fulani',
 'Uganda',
 'KNU',
 'Abugbe',
 'Mara',
 'Libya',
 'Fulani',
 'Gony',
 'NUG',
 'UBA',
 'Borana',
 'Bonta',
 'Balanda',
 'Luac',
 'Cie',
 'LeJ',
 'India',
 'Choa',
 'Dar',
 'Janjaweed',
 'Luac',
 'Government',
 'Kawahla',
 'Black',
 'Los',
 'FPIC',
 'NSCN-IM',
 'ARSA',
 'Cartel',
 'Nova',
 'Choa',
 'IS',
 'AFP-Gutabara',
 'Los',
 'Misseriya',
 'Misseriya',
 'PIJ',
 'Gulf',
 'Toposa',
 'Al-Shabaab',
 'Cartel',
 'FDBC',
 'Murle',
 'Kusasi',
 'Cartel',
 'Jalisco',
 'Bonde',
 'Russia',
 'Jalisco',
 'Nambelo',
 'Agatu',
 'Amigos',
 'Deebam',
 'Farmers',
 'Los',
 'GATIA',
 'Los',
 'M23',
 'Fulani',
 'Fano',
 'RCSS',
 'Los',
 'Government',
 'Chawai',
 'Aiyala',
 'Ikot-Offiong',
 'Twic',
 'GATIA',
 'Government',
 'Togo',
 'Fulani',
 'Burji',
 'Gimir',
 'FPIC',
 'Mara',
 'Buya',
 'Giants',
 'Teke',
 'Government',
 'Government',
 'Amigos',
 'Mara',
 'SPLM',
 'Misseriya',
 'Mayi',
 'Kuboma',
 'Kata',
 'Comando',
 'Ijaw',
 '400',
 'ANCDH',
 'IS',
 'Renamo',
 'Misseriya',
 'FDN',
 'Luac',
 'Apuk',
 'Nova',
 'VDP',
 'Luac',
 'SSC-Khatumo',
 'Mozambique',
 'Daoussak',
 'Hamas',
 'Bonde',
 'VHP',
 'Russia',
 'M23',
 'Mauritania',
 'Comando',
 'Mobondo',
 'Azande',
 'Carteles',
 'Fulani',
 'Kuki',
 'Los',
 'Lengola',
 'Government',
 'Karimjo',
 'Hausa',
 'Shia',
 'Djerma',
 'Anuak',
 'Ethiopia',
 'RSF',
 'Dinka',
 'Los',
 'Mali',
 'Banunu',
 'Russia',
 'Beni',
 'Deir',
 '5',
 'Supporters',
 'AGC',
 'Grand',
 'DZ',
 'Los',
 'Habaniya',
 'Chain',
 'Terre',
 'G',
 'Arab',
 'Fulani']

In [72]:
len(countries)

515

In [73]:
!pip install pycountry-convert

Collecting pycountry-convert
  Obtaining dependency information for pycountry-convert from https://files.pythonhosted.org/packages/9b/e7/26c14899a43c34e04a58e3772007afe79dbd64fac15d2fbaeedff24082f2/pycountry_convert-0.7.2-py3-none-any.whl.metadata
  Downloading pycountry_convert-0.7.2-py3-none-any.whl.metadata (7.2 kB)
Collecting pprintpp>=0.3.0 (from pycountry-convert)
  Obtaining dependency information for pprintpp>=0.3.0 from https://files.pythonhosted.org/packages/4e/d1/e4ed95fdd3ef13b78630280d9e9e240aeb65cc7c544ec57106149c3942fb/pprintpp-0.4.0-py2.py3-none-any.whl.metadata
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl.metadata (7.9 kB)
Collecting pycountry>=16.11.27.1 (from pycountry-convert)
  Obtaining dependency information for pycountry>=16.11.27.1 from https://files.pythonhosted.org/packages/b1/ec/1fb891d8a2660716aadb2143235481d15ed1cbfe3ad669194690b0604492/pycountry-24.6.1-py3-none-any.whl.metadata
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pytest>=3.4.0 in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pycountry-convert) (7.4.0)
Collecting pytest-mock>=1.6.3 (from pycountry-convert)
  Obtaining dependency information for pytest-mock>=1.6.3 from https://files.pythonhosted.org/packages/f2/3b/b26f90f74e2986a82df6e7ac7e319b8ea7ccece1caec9f8ab6104dc70603/pytest_mock-3.14.0-py3-none-any.whl.metadata
  Downloading pytest_mock-3.14.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pytest-cov>=2.5.1 (from pycountry-convert)
  Obtaining dependency information for pytest-cov>=2.5.1 from https://files.pythonhosted.org/packages/78/3a/af5b4fa5961d9a1e6237b530eb87dd04aea6eb83da09d2a4073d81b54ccf/pytest_cov-5.0.0-py3-none-any.whl.metadata
  Downloading pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting repoze.lru>=0.7 (from pycountry-convert)
  Obtaining dependency information for repoze.lru>=0.7 from https://files.pythonhosted.org/packages/b0/30/6cc0c95f0b59ad4b3b9163bff7cdcf793cc96fac64cf398ff26271f5cf5e/repoze.lru-0.7-py3-none-any.whl.metadata
  Downloading repoze.lru-0.7-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: wheel>=0.30.0 in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pycountry-convert) (0.38.4)
Requirement already satisfied: iniconfig in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pytest>=3.4.0->pycountry-convert) (23.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: colorama in c:\users\piercev1\appdata\local\anaconda3\lib\site-packages (from pytest>=3.4.0->pycountry-convert) (0.4.6)
Collecting coverage[toml]>=5.2.1 (from pytest-cov>=2.5.1->pycountry-convert)
  Obtaining dependency information for coverage[toml]>=5.2.1 from https://files.pythonhosted.org/packages/3d/63/2d9474c5d2bc866309728de71cbd5fbf64824de88f8a35c8a76a7e658ac4/coverage-7.5.3-cp311-cp311-win_amd64.whl.metadata
  Downloading coverage-7.5.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Downloading pycountry_convert-0.7.2-py3-none-any.whl (13 kB)
Downloading pprintpp-0.4.0-py2.py3-none-any.whl (16 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   -- ------------------------------------- 0.3/6.3 MB 9.9 MB/s eta 0:00:01
   ------ --------------------------------- 1.0/6.3 MB 13.0 MB/s eta 0:00:01
   ---------------- ----------------------- 2.5/6.3 MB 20.2 MB/s eta 0:00:01
   ----------------------- ---------------- 3.8/6.3 MB 22.0 MB/s eta 0:00:01
   ------------------------------ --------- 4.9/6.3 MB 22.2 MB/s eta 0:00:01
   ---------------------------------------  6.2/6.3 MB 23.2 MB/s eta 0:00:01
   ---------------------------------------  6.3/6.3 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 19.3 MB/s eta 0:00:00
Downloading pytest_cov-5.0.0-py3-none-any.whl (21 kB)
Downloading pytest_mock-3.14.0-py3-none-any.whl (9.9 kB)
Downloading repoze.lru-0.7-py3-none-any.whl (10 kB)
Downloading coverage-7.5.3-cp311-cp311-win_amd64.whl (207 kB)
   ---------------------------------------- 0.0/207.5 kB ? eta -:--:--
   ---------------------------------------- 207.5/207.5 kB ? eta 0:00:00
Installing collected packages: repoze.lru, pprintpp, pycountry, coverage, pytest-mock, pytest-cov, pycountry-convert
Successfully installed coverage-7.5.3 pprintpp-0.4.0 pycountry-24.6.1 pycountry-convert-0.7.2 pytest-cov-5.0.0 pytest-mock-3.14.0 repoze.lru-0.7

In [74]:
import pycountry_convert as pc

In [75]:
rec_countries = [entry for entry in countries if pc.country_name_to_country_alpha2(entry, cn_name_format="default")]

TypeError: argument of type 'functools._lru_cache_wrapper' is not iterable

In [76]:
type(countries)

list

In [77]:
import pycountry



# Filter out recognized country names
recognized_countries = []
for entry in countries:
    try:
        country = pycountry.countries.lookup(entry)
        recognized_countries.append(entry)
    except LookupError:
        pass

print(recognized_countries)

['Syria', 'IS', 'IS', 'Afghanistan', 'Afghanistan', 'Syria', 'India', 'Mozambique', 'India', 'India', 'Nigeria', 'Somalia', 'Kenya', 'Ethiopia', 'Nigeria', 'Cameroon', 'Iran', 'IS', 'India', 'Rwanda', 'Thailand', 'Mali', 'Mali', 'Niger', 'IS', 'IS', 'Yemen', 'Libya', 'Chad', 'Iraq', 'Myanmar', 'Algeria', 'Algeria', 'Pakistan', 'Pakistan', 'Pakistan', 'Yemen', 'Chad', 'Colombia', 'Somalia', 'Somalia', 'Tunisia', 'Egypt', 'Israel', 'Niger', 'Philippines', 'Philippines', 'Philippines', 'Iran', 'Myanmar', 'Myanmar', 'Tunisia', 'Myanmar', 'Azerbaijan', 'Ukraine', 'Israel', 'IS', 'Indonesia', 'Cameroon', 'Syria', 'Burundi', 'Angola', 'Cameroon', 'Senegal', 'China', 'Sudan', 'Uganda', 'India', 'Lebanon', 'Iran', 'Tanzania', 'Ethiopia', 'IS', 'Bangladesh', 'Myanmar', 'Morocco', 'Benin', '400', 'IS', 'Nigeria', 'Myanmar', 'Kyrgyzstan', 'Myanmar', 'Iran', 'Peru', 'Uganda', 'Libya', 'India', 'IS', 'Togo', '400', 'IS', 'Mozambique', 'Mauritania', 'Ethiopia', 'Mali', 'DZ']

In [78]:
len(recognized_countries)

97

In [82]:
uppsala_filtered.to_excel(os.path.join(path, 'uppsala_filtered.xlsx'), index = False)

In [83]:
uppsala.country_id.unique()

array([615, 625, 651, 500, 530, 516, 432, 483, 520, 581, 522, 452, 541,
       551, 560, 572, 552, 475, 571, 461, 510, 540, 436, 490, 600, 471,
       482, 451, 517, 433, 435, 501, 404, 437, 484, 450, 910, 775, 800,
       771, 770, 750, 702, 812, 940, 230, 200, 260, 210,  52, 346, 345,
       344, 700, 780, 710, 790,  51, 811, 365, 150, 630, 645,  92, 840,
        95, 850,  93, 690, 640, 670, 663, 373, 371, 135, 666, 660, 220,
       160, 359,  70, 360,  41,  90, 372, 101, 678, 420, 565, 531, 438,
       140,  20, 130, 325, 338, 100, 692, 570, 704, 703, 760, 145,  91,
       339, 343, 580, 616,   2, 652, 694, 620, 110, 626, 696, 820, 369,
       439, 211, 380, 900, 434, 305, 290], dtype=int64)

In [84]:
len(uppsala.country_id.unique())

124

In [85]:
uppsala_filtered.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
267518,320838,SYR-2020-1-11973-0,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,0,0,12,0,12,12,12,652,NaN
267551,320874,SYR-2020-1-11973-5,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,2,0,0,0,2,2,2,652,NaN
267552,320875,AFG-2020-2-14637-1,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267570,320896,SYR-2020-3-14200-0,2020,False,Clear,3,4456,13299,Syrian insurgents - Civilians,4456,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267571,320897,AFG-2020-2-14637-0,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,1,0,0,0,1,1,1,NaN,NaN

In [86]:
len(uppsala_filtered.country_id.unique())

85

In [87]:
print("a" + "_")

a_

In [88]:
print("a" + "_" + "b")

a_b

In [90]:
type(uppsala_filtered.country_id)

pandas.core.series.Series

In [91]:
type(as.string(uppsala_filtered.country_id))

SyntaxError: invalid syntax (3974604967.py, line 1)

In [92]:
type(str(uppsala_filtered.country_id))

str

In [93]:
type(uppsala_filtered.year)

pandas.core.series.Series

In [95]:
type(str(uppsala_filtered.year))

str

In [96]:
uppsala_filtered['cyid'] = str(uppsala_filtered.country_id) + "_" + str(uppsala_filtered.year)

C:\Users\piercev1\AppData\Local\Temp\ipykernel_4016\4063533172.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uppsala_filtered['cyid'] = str(uppsala_filtered.country_id) + "_" + str(uppsala_filtered.year)

In [97]:
uppsala_filtered

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob,cyid
267518,320838,SYR-2020-1-11973-0,2020,True,Clear,1,299,299,Syria: Government,11973,...,0,0,12,0,12,12,12,652,NaN,267518 652\n267551 652\n267552 652\n2...
267551,320874,SYR-2020-1-11973-5,2020,True,Clear,1,299,299,Syria: Government,11973,...,2,0,0,0,2,2,2,652,NaN,267518 652\n267551 652\n267552 652\n2...
267552,320875,AFG-2020-2-14637-1,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,0,0,1,0,1,1,1,NaN,NaN,267518 652\n267551 652\n267552 652\n2...
267570,320896,SYR-2020-3-14200-0,2020,False,Clear,3,4456,13299,Syrian insurgents - Civilians,4456,...,0,0,1,0,1,1,1,NaN,NaN,267518 652\n267551 652\n267552 652\n2...
267571,320897,AFG-2020-2-14637-0,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,1,0,0,0,1,1,1,NaN,NaN,267518 652\n267551 652\n267552 652\n2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349728,515726,RUS-2023-1-14117-791.1,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,0,2,0,0,2,2,2,365,369.0,267518 652\n267551 652\n267552 652\n2...
349729,515884,RUS-2022-1-14117-992,2022,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,0,1,0,0,1,1,1,365,369.0,267518 652\n267551 652\n267552 652\n2...
349730,515995,ISR-2023-1-477-1247,2023,True,Clear,1,234,234,Israel: Palestine,477,...,1,0,0,0,1,1,1,666,NaN,267518 652\n267551 652\n267552 652\n2...
349731,516027,RUS-2023-1-14117-793,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,6,0,0,0,6,7,6,365,369.0,267518 652\n267551 652\n267552 652\n2...
349732,516031,FRN-2023-2-17630-45,2023,True,Clear,2,17630,16009,DZ Mafia - Yoda,17630,...,0,2,0,0,2,2,2,NaN,NaN,267518 652\n267551 652\n267552 652\n2...

In [99]:
uppsala_filtered

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
267518,320838,SYR-2020-1-11973-0,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,0,0,12,0,12,12,12,652,NaN
267551,320874,SYR-2020-1-11973-5,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,2,0,0,0,2,2,2,652,NaN
267552,320875,AFG-2020-2-14637-1,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267570,320896,SYR-2020-3-14200-0,2020,False,Clear,3,4456,13299,Syrian insurgents - Civilians,4456,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
267571,320897,AFG-2020-2-14637-0,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,1,0,0,0,1,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349728,515726,RUS-2023-1-14117-791.1,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-03-10,0,2,0,0,2,2,2,365,369.0
349729,515884,RUS-2022-1-14117-992,2022,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2022-12-16,0,1,0,0,1,1,1,365,369.0
349730,515995,ISR-2023-1-477-1247,2023,True,Clear,1,234,234,Israel: Palestine,477,...,2023-10-07,1,0,0,0,1,1,1,666,NaN
349731,516027,RUS-2023-1-14117-793,2023,True,Clear,1,13243,13243,Russia - Ukraine,14117,...,2023-12-31,6,0,0,0,6,7,6,365,369.0
349732,516031,FRN-2023-2-17630-45,2023,True,Clear,2,17630,16009,DZ Mafia - Yoda,17630,...,2023-05-03,0,2,0,0,2,2,2,NaN,NaN

In [104]:
uppsala_filtered.country_id

267518    652
267551    652
267552    652
267570    652
267571    652
         ...
349728    369
349729    369
349730    666
349731    369
349732    230
Name: country_id, Length: 73984, dtype: int64

In [103]:
cyid

'267518    652\n267551    652\n267552    652\n267570    652\n267571    652\n         ... \n349728    369\n349729    369\n349730    666\n349731    369\n349732    230\nName: country_id, Length: 73984, dtype: int64_'

In [106]:
uppsala_filtered_excel = pd.read_excel(os.path.join(path, "uppsala_filtered.xlsx"))

In [107]:
uppsala_filtered_excel.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
0,320838,SYR-2020-1-11973-0,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,0,0,12,0,12,12,12,652.0,NaN
1,320874,SYR-2020-1-11973-5,2020,True,Clear,1,299,299,Syria: Government,11973,...,2020-01-01,2,0,0,0,2,2,2,652.0,NaN
2,320875,AFG-2020-2-14637-1,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
3,320896,SYR-2020-3-14200-0,2020,False,Clear,3,4456,13299,Syrian insurgents - Civilians,4456,...,2020-01-01,0,0,1,0,1,1,1,NaN,NaN
4,320897,AFG-2020-2-14637-0,2020,True,Clear,2,14637,13616,IS - SDF,14637,...,2020-01-01,1,0,0,0,1,1,1,NaN,NaN

In [108]:
uppsala_filtered_excel.country_id

0        652
1        652
2        652
3        652
4        652
        ...
73979    369
73980    369
73981    666
73982    369
73983    230
Name: country_id, Length: 73984, dtype: int64

In [109]:
cn = str(uppsala_filtered_excel.country_id) + "_"

In [110]:
cn

'0        652\n1        652\n2        652\n3        652\n4        652\n        ... \n73979    369\n73980    369\n73981    666\n73982    369\n73983    230\nName: country_id, Length: 73984, dtype: int64_'

In [111]:
cyid = str(uppsala_filtered_excel.country_id) + '_' + str(uppsala_filtered_excel.year)

In [112]:
cyid

'0        652\n1        652\n2        652\n3        652\n4        652\n        ... \n73979    369\n73980    369\n73981    666\n73982    369\n73983    230\nName: country_id, Length: 73984, dtype: int64_0        2020\n1        2020\n2        2020\n3        2020\n4        2020\n         ... \n73979    2023\n73980    2022\n73981    2023\n73982    2023\n73983    2023\nName: year, Length: 73984, dtype: int64'

In [113]:
cyid_full = uppsala_filtered_excel['country_id'].astype(str) + "_" + uppsala_filtered_excel['year'].astype(str)

In [115]:
cyid_full

0        652_2020
1        652_2020
2        652_2020
3        652_2020
4        652_2020
           ...
73979    369_2023
73980    369_2022
73981    666_2023
73982    369_2023
73983    230_2023
Length: 73984, dtype: object

In [116]:
cyid = cyid_full.unique()

In [117]:
cyid

array(['652_2020', '700_2020', '439_2020', '70_2021', '750_2021',
       '140_2023', '70_2023', '541_2020', '750_2020', '645_2020',
       '501_2020', '475_2020', '520_2020', '530_2020', '471_2020',
       '490_2020', '800_2020', '432_2020', '625_2020', '626_2020',
       '70_2020', '436_2020', '700_2021', '516_2020', '483_2020',
       '678_2020', '620_2020', '482_2020', '775_2020', '615_2020',
       '770_2020', '100_2020', '135_2020', '140_2020', '616_2020',
       '651_2020', '630_2020', '666_2020', '560_2020', '640_2020',
       '840_2020', '373_2020', '369_2020', '365_2020', '850_2020',
       '540_2020', '435_2020', '433_2020', '484_2020', '450_2020',
       '670_2020', '438_2020', '101_2020', '572_2020', '660_2020',
       '771_2020', '41_2020', '371_2020', '510_2020', '305_2020',
       '552_2020', '437_2020', '580_2020', '150_2020', '600_2020',
       '434_2020', '91_2020', '490_2021', '678_2021', '541_2021',
       '520_2021', '651_2021', '432_2021', '439_2021', '770_2021',
       '482_2021', '140_2021', '436_2021', '471_2021', '615_2021',
       '645_2021', '41_2021', '475_2021', '652_2021', '369_2021',
       '771_2021', '501_2021', '640_2021', '530_2021', '625_2021',
       '616_2021', '540_2021', '516_2021', '840_2021', '373_2021',
       '130_2021', '100_2021', '800_2021', '620_2021', '626_2021',
       '600_2021', '630_2021', '775_2021', '850_2021', '365_2021',
       '483_2021', '910_2021', '434_2021', '438_2021', '666_2021',
       '702_2021', '703_2021', '500_2021', '371_2021', '135_2021',
       '517_2021', '92_2021', '91_2021', '572_2021', '522_2021',
       '560_2021', '510_2021', '101_2021', '670_2021', '433_2021',
       '541_2022', '700_2022', '490_2022', '439_2022', '100_2022',
       '432_2022', '678_2022', '70_2022', '750_2022', '652_2022',
       '530_2022', '520_2022', '775_2022', '800_2022', '850_2022',
       '369_2022', '640_2022', '770_2022', '373_2022', '371_2022',
       '702_2022', '501_2022', '475_2022', '615_2022', '483_2022',
       '471_2022', '625_2022', '436_2022', '626_2022', '645_2022',
       '840_2022', '620_2022', '540_2022', '600_2022', '434_2022',
       '452_2022', '666_2022', '696_2022', '482_2022', '101_2022',
       '651_2022', '516_2022', '140_2022', '150_2021', '510_2022',
       '771_2022', '41_2022', '365_2022', '92_2022', '130_2022',
       '703_2022', '451_2021', '560_2022', '910_2022', '630_2022',
       '531_2022', '790_2022', '461_2022', '484_2022', '517_2022',
       '91_2022', '500_2022', '135_2022', '616_2022', '90_2022', '2_2022',
       '145_2021', '290_2022', '700_2023', '432_2023', '439_2023',
       '369_2023', '750_2023', '475_2023', '471_2023', '541_2023',
       '530_2023', '775_2023', '490_2023', '666_2023', '520_2023',
       '678_2023', '461_2023', '436_2023', '652_2023', '501_2023',
       '770_2023', '771_2023', '640_2023', '645_2023', '800_2023',
       '516_2023', '100_2023', '365_2023', '101_2023', '840_2023',
       '500_2023', '482_2023', '572_2022', '850_2023', '651_2023',
       '572_2023', '373_2023', '435_2023', '626_2023', '625_2023',
       '483_2023', '434_2023', '135_2023', '91_2023', '560_2023',
       '371_2023', '130_2023', '41_2023', '630_2023', '540_2023',
       '615_2023', '620_2023', '145_2023', '452_2023', '910_2023',
       '670_2023', '660_2023', '220_2023', '211_2023', '710_2023',
       '372_2023', '616_2023', '600_2023', '230_2023'], dtype=object)

In [118]:
len(cyid)

255

In [123]:
cyid_list = cyid

In [124]:
len(cyid_list)

255

In [119]:
ewp_aug = ewp

In [121]:
ewp_aug['cyid'] = ewp_aug['COW'].astype(str) + "_" + ewp_aug['year'].astype(str)

In [122]:
ewp_aug

,country,COW,year,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,...,candidaterestriction,social_power_dist,ses_power_dist,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln,cyid
0,Afghanistan,700,2020,1,1,0,0,0,0,0,...,1,1,-0.910,0.001816,17.427736,-2.359148,2,4.605170,10.153468,700_2020
1,Democratic Republic of Congo,490,2020,1,1,0,0,0,0,1,...,1,1,-0.695,0.040775,18.240043,-2.083498,3,4.077537,6.042633,490_2020
2,Pakistan,770,2020,1,1,0,0,0,0,0,...,1,1,-1.337,0.038073,19.164214,-3.111684,1,4.276666,5.293305,770_2020
3,Yemen,679,2020,0,0,0,0,1,0,0,...,1,1,-1.210,-0.028943,17.164070,-2.803119,0,3.367296,8.417152,679_2020
4,South Sudan,626,2020,1,1,0,0,0,0,1,...,1,1,-1.664,-0.006500,16.223777,-1.570666,2,2.079442,6.285998,626_2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Lithuania,368,2023,0,0,1,1,0,0,0,...,1,0,1.388,0.034557,14.919486,-1.209574,4,3.433987,0.000000,368_2023
158,Denmark,390,2023,0,0,1,1,0,0,0,...,1,0,1.847,0.032002,15.615046,-1.575342,4,6.963190,0.000000,390_2023
159,Norway,385,2023,0,0,1,1,0,0,0,...,1,0,2.383,0.025650,15.538799,-2.087887,4,4.762174,0.000000,385_2023
160,Estonia,366,2023,0,0,1,1,0,0,0,...,1,0,1.436,0.062133,14.263249,-1.180223,4,3.433987,0.000000,366_2023
161,Slovenia,349,2023,0,0,1,1,0,0,0,...,1,0,1.181,0.060197,14.663403,-1.173667,4,3.433987,0.000000,349_2023

In [125]:
ewp_filtered = ewp[ewp['cyid'].isin(cyid_list)]

In [126]:
ewp_filtered

,country,COW,year,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,...,candidaterestriction,social_power_dist,ses_power_dist,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln,cyid
0,Afghanistan,700,2020,1,1,0,0,0,0,0,...,1,1,-0.910,0.001816,17.427736,-2.359148,2,4.605170,10.153468,700_2020
1,Democratic Republic of Congo,490,2020,1,1,0,0,0,0,1,...,1,1,-0.695,0.040775,18.240043,-2.083498,3,4.077537,6.042633,490_2020
2,Pakistan,770,2020,1,1,0,0,0,0,0,...,1,1,-1.337,0.038073,19.164214,-3.111684,1,4.276666,5.293305,770_2020
4,South Sudan,626,2020,1,1,0,0,0,0,1,...,1,1,-1.664,-0.006500,16.223777,-1.570666,2,2.079442,6.285998,626_2020
5,Sudan,625,2020,1,1,0,0,0,0,1,...,1,1,-0.241,-0.025805,17.544358,-3.347368,1,4.143135,5.509388,625_2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,France,220,2023,0,0,1,1,0,0,0,...,1,0,1.273,0.050711,18.021265,-2.233204,4,7.072422,0.000000,220_2023
123,Georgia,372,2023,0,1,1,1,0,0,0,...,0,1,0.229,0.078694,15.181669,-1.685967,3,3.433987,0.000000,372_2023
132,Belgium,211,2023,0,0,1,1,0,0,0,...,1,0,1.830,0.044787,16.276850,-1.122811,4,5.257495,0.000000,211_2023
142,Swaziland,572,2023,0,0,1,0,0,0,1,...,1,1,-0.867,0.054523,14.158715,-1.857737,3,3.988984,0.000000,572_2023
152,Armenia,371,2023,0,0,1,1,0,0,0,...,0,0,0.717,0.040298,14.974655,-1.978921,3,3.433987,0.000000,371_2023

In [127]:
ewp_final = ewp_filtered.drop(columns = ['cyid'])

In [128]:
ewp_final

,country,COW,year,anymk.ongoing,anymk.ever,freemove_men4,freemove_women4,reg.mna,reg.eap,reg.afr,...,partyban,candidaterestriction,social_power_dist,ses_power_dist,gdppcgrowth.combined,popsize.ln.combined,tradeshare.ln.combined,religiousfreedom,countryage.ln,battledeaths.ln
0,Afghanistan,700,2020,1,1,0,0,0,0,0,...,4,1,1,-0.910,0.001816,17.427736,-2.359148,2,4.605170,10.153468
1,Democratic Republic of Congo,490,2020,1,1,0,0,0,0,1,...,4,1,1,-0.695,0.040775,18.240043,-2.083498,3,4.077537,6.042633
2,Pakistan,770,2020,1,1,0,0,0,0,0,...,4,1,1,-1.337,0.038073,19.164214,-3.111684,1,4.276666,5.293305
4,South Sudan,626,2020,1,1,0,0,0,0,1,...,3,1,1,-1.664,-0.006500,16.223777,-1.570666,2,2.079442,6.285998
5,Sudan,625,2020,1,1,0,0,0,0,1,...,3,1,1,-0.241,-0.025805,17.544358,-3.347368,1,4.143135,5.509388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,France,220,2023,0,0,1,1,0,0,0,...,4,1,0,1.273,0.050711,18.021265,-2.233204,4,7.072422,0.000000
123,Georgia,372,2023,0,1,1,1,0,0,0,...,4,0,1,0.229,0.078694,15.181669,-1.685967,3,3.433987,0.000000
132,Belgium,211,2023,0,0,1,1,0,0,0,...,4,1,0,1.830,0.044787,16.276850,-1.122811,4,5.257495,0.000000
142,Swaziland,572,2023,0,0,1,0,0,0,1,...,0,1,1,-0.867,0.054523,14.158715,-1.857737,3,3.988984,0.000000
152,Armenia,371,2023,0,0,1,1,0,0,0,...,4,0,0,0.717,0.040298,14.974655,-1.978921,3,3.433987,0.000000

In [130]:
ewp_final.to_csv(os.path.join(path, "ewp_final.csv"), index = False)